# Generated by Django 5.1.7 on 2025-05-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
